version: '3'
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./config/livekit.yaml:/etc/livekit.yaml:ro
    restart: unless-stopped
    networks:
      - livekit-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge

volumes:
  redis-data:
