port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: redis:6379
  username: ""
  password: ""

keys:
  ${API_KEY}: ${API_SECRET}  # Using env variables directly

logging:
  json: false
  level: info
