name: LiveKit Server Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy LiveKit Server to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            echo "Navigating to project directory"
            cd /path/to/your/livekit-project  # Update with actual server path

            echo "Pulling latest changes from Git"
            git pull origin main

            echo "Stopping and removing previous LiveKit server container"
            docker-compose down

            echo "Removing old LiveKit server image"
            docker rmi livekit/livekit-server:latest || true

            echo "Pulling latest LiveKit image"
            docker pull livekit/livekit-server:latest

            echo "Creating .env file"
            cat <<EOF > .env
            API_KEY=${{ secrets.API_KEY }}
            API_SECRET=${{ secrets.API_SECRET }}
            EOF

            echo "Starting LiveKit server with Docker Compose"
            docker-compose up -d --build

            echo "LiveKit server deployed successfully"
