name: LiveKit Server Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Deploy LiveKit Server to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            echo "Navigating to project directory"
            cd /path/to/your/livekit-project  # Update with actual server path

            echo "Pulling latest changes from Git"
            git pull origin main

            echo "Stopping and removing previous LiveKit server container"
            docker-compose stop livekit  # Stops only LiveKit, keeps Redis running
            docker-compose rm -f livekit # Removes old LiveKit container

            echo "Creating .env file"
            cat <<EOF > .env
            API_KEY=${{ secrets.API_KEY }}
            API_SECRET=${{ secrets.API_SECRET }}
            EOF

            echo "Building and starting LiveKit server"
            docker-compose up -d --build livekit

            echo "LiveKit server deployed successfully"
