# .github/workflows/deploy.yml
name: LiveKit Server Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy LiveKit Server to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            echo "Creating .env file"
            cat <<EOF > .env
            API_KEY=${{ secrets.API_KEY }}
            API_SECRET=${{ secrets.API_SECRET }}
            EOF

            echo "Verifying .env file contents"
            cat .env

            echo "Checking for Docker Compose"
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose"
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Starting LiveKit server with Docker Compose"
            docker-compose pull
            docker-compose up -d --build

            echo "LiveKit server deployed successfully"